In [1]:
import math
import numpy as np
import random
import time
import re

In [2]:
MySentence="Nepal does not have direct access to the sea because it is a landlocked country."

# Creating Embeddings
--> Considering embedding vector size 4

In [4]:
embedding_dim=3
low=-0.1
high=0.3
random.seed(time.time())

In [5]:
x = round(random.uniform(low,high),3)
print(x)

0.28


In [7]:
def tokenize(text):
    return re.findall(r"\w+|[^\w\s]", text)
Tokens=tokenize(MySentence)
Tokens

['Nepal',
 'does',
 'not',
 'have',
 'direct',
 'access',
 'to',
 'the',
 'sea',
 'because',
 'it',
 'is',
 'a',
 'landlocked',
 'country',
 '.']

# Calculating Embeddings of each tokens

In [ ]:
embeddings=[[round(random.uniform(low,high),3) for _ in range(embedding_dim)] for _ in Tokens]
embeddings_vector_array=np.array(embeddings)
embeddings_vector_array

array([[ 0.297, -0.004,  0.258],
       [ 0.194,  0.151,  0.124],
       [-0.055,  0.164,  0.067],
       [ 0.265,  0.237,  0.189],
       [-0.008,  0.272, -0.035],
       [-0.083,  0.281,  0.047],
       [-0.099,  0.154,  0.113],
       [ 0.261,  0.083, -0.002],
       [ 0.158,  0.23 ,  0.132],
       [-0.047,  0.199,  0.013],
       [ 0.244,  0.093,  0.068],
       [ 0.207,  0.187,  0.049],
       [-0.037,  0.087,  0.038],
       [ 0.172,  0.108,  0.25 ],
       [ 0.29 ,  0.135,  0.223],
       [ 0.036,  0.234,  0.164]])

In [9]:
# Save txt
np.savetxt("token_embedding.txt",embeddings_vector_array,fmt="%.3f")

# Weight Matrices
* Learnable parameters that transform vectors having dimention embedding_dim x embedding_dim

In [10]:
weightQ=np.array([
    [round(random.uniform(-1,2),2) for _ in range(embedding_dim)] for _ in range(embedding_dim)
])
weightK=np.array([
    [round(random.uniform(-1,2),2) for _ in range(embedding_dim)] for _ in range(embedding_dim)
])
weightV=np.array([
    [round(random.uniform(-1,2),2) for _ in range(embedding_dim)] for _ in range(embedding_dim)
])
print(weightQ)
print(weightK)
print(weightV)

[[ 1.56  1.56  1.23]
 [ 0.07 -0.12 -0.63]
 [-0.14  1.04  0.8 ]]
[[ 0.46  0.98  0.56]
 [ 1.27  1.7   0.79]
 [ 1.34 -0.71 -0.77]]
[[ 0.04  0.12  0.27]
 [ 0.51  1.07  1.09]
 [-0.66  1.56 -0.82]]


In [11]:
#save weights
np.savetxt("weight_q.txt",weightQ,fmt="%.3f")
np.savetxt("weight_k.txt",weightK,fmt="%.3f")
np.savetxt("weight_v.txt",weightV,fmt="%.3f")

# Calculating Query, Key And Values Vectors

In [12]:
Q=embeddings_vector_array@weightQ
K=embeddings_vector_array@weightK
V=embeddings_vector_array@weightV
Q

array([[ 0.42692,  0.73212,  0.57423],
       [ 0.29585,  0.41348,  0.24269],
       [-0.0837 , -0.0358 , -0.11737],
       [ 0.40353,  0.58152,  0.32784],
       [ 0.01146, -0.08152, -0.2092 ],
       [-0.11639, -0.11432, -0.24152],
       [-0.15948, -0.0554 , -0.12839],
       [ 0.41325,  0.39512,  0.26714],
       [ 0.2441 ,  0.35616,  0.15504],
       [-0.06121, -0.08368, -0.17278],
       [ 0.37763,  0.4402 ,  0.29593],
       [ 0.32915,  0.35144,  0.176  ],
       [-0.05695, -0.02864, -0.06992],
       [ 0.24088,  0.51536,  0.34352],
       [ 0.43063,  0.66812,  0.45005],
       [ 0.04958,  0.19864,  0.02806]])

# Calculating raw attention score

In [13]:
Attention_score=Q@ K.T
Attention_score

array([[ 0.25736936,  0.52963259,  0.27335997,  0.78468261,  0.61316077,
         0.50869652,  0.17866181,  0.50918293,  0.65903231,  0.38271263,
         0.48329271,  0.65559052,  0.13439107,  0.3569884 ,  0.57378783,
         0.50479517],
       [ 0.17437643,  0.31278789,  0.16546614,  0.46466131,  0.34306325,
         0.29681775,  0.11910115,  0.28236   ,  0.38809566,  0.21988294,
         0.27767096,  0.37362516,  0.08227344,  0.23267899,  0.3491576 ,
         0.30786969],
       [-0.03939869, -0.06581811, -0.03471477, -0.09782287, -0.06970043,
        -0.06129281, -0.02581897, -0.05793816, -0.08130438, -0.0451214 ,
        -0.05791421, -0.07725753, -0.01731696, -0.05112033, -0.07467422,
        -0.06523138],
       [ 0.23973045,  0.43250666,  0.228652  ,  0.64245018,  0.47558418,
         0.41077591,  0.16399988,  0.3914403 ,  0.53674704,  0.30449459,
         0.38435514,  0.51742113,  0.11364418,  0.32046596,  0.48216566,
         0.42522987],
       [ 0.00465596, -0.05183172, -0

# Scaling the score with key vector dimension

In [14]:
Attention_score_scaled=Attention_score/np.sqrt(K.shape[0])
Attention_score_scaled

array([[ 0.06434234,  0.13240815,  0.06833999,  0.19617065,  0.15329019,
         0.12717413,  0.04466545,  0.12729573,  0.16475808,  0.09567816,
         0.12082318,  0.16389763,  0.03359777,  0.0892471 ,  0.14344696,
         0.12619879],
       [ 0.04359411,  0.07819697,  0.04136654,  0.11616533,  0.08576581,
         0.07420444,  0.02977529,  0.07059   ,  0.09702392,  0.05497074,
         0.06941774,  0.09340629,  0.02056836,  0.05816975,  0.0872894 ,
         0.07696742],
       [-0.00984967, -0.01645453, -0.00867869, -0.02445572, -0.01742511,
        -0.0153232 , -0.00645474, -0.01448454, -0.02032609, -0.01128035,
        -0.01447855, -0.01931438, -0.00432924, -0.01278008, -0.01866856,
        -0.01630784],
       [ 0.05993261,  0.10812667,  0.057163  ,  0.16061254,  0.11889605,
         0.10269398,  0.04099997,  0.09786008,  0.13418676,  0.07612365,
         0.09608878,  0.12935528,  0.02841104,  0.08011649,  0.12054142,
         0.10630747],
       [ 0.00116399, -0.01295793, -0

# Applying Softmax to calculate attention weights-->Probabilities

In [15]:
type(Attention_score_scaled)
print(type(Attention_score_scaled))
print(np.shape(Attention_score_scaled))

<class 'numpy.ndarray'>
(16, 16)


In [16]:
def softmax(xi):
    exp_x = np.exp(xi - np.max(xi, axis=1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

attention_weights=softmax(Attention_score_scaled)
attention_weights

array([[0.05931186, 0.06348954, 0.05954944, 0.06766964, 0.06482927,
        0.0631581 , 0.0581562 , 0.06316578, 0.065577  , 0.06119987,
        0.06275826, 0.0655206 , 0.05751609, 0.06080756, 0.06419427,
        0.06309653],
       [0.06093798, 0.06308351, 0.06080238, 0.06552474, 0.06356279,
        0.06283215, 0.06010168, 0.06260546, 0.06428243, 0.0616352 ,
        0.06253211, 0.0640503 , 0.05955086, 0.06183269, 0.06365971,
        0.063006  ],
       [0.06278503, 0.06237172, 0.0628586 , 0.06187466, 0.06231121,
        0.06244232, 0.06299855, 0.06249471, 0.06213071, 0.06269527,
        0.06249508, 0.0621936 , 0.06313259, 0.06260132, 0.06223378,
        0.06238086],
       [0.0603199 , 0.06329815, 0.06015307, 0.06670914, 0.06398352,
        0.0629552 , 0.05918863, 0.06265162, 0.06496939, 0.06130449,
        0.06254074, 0.06465625, 0.05844818, 0.06154976, 0.06408888,
        0.0631831 ],
       [0.06326095, 0.06237386, 0.06285338, 0.06201214, 0.06185329,
        0.06233441, 0.06320176, 

# Finally Calculating Context Vector

In [17]:
context_vector=attention_weights@V
context_vector

array([[0.01878649, 0.35594242, 0.12404488],
       [0.01813613, 0.35525584, 0.12258229],
       [0.01759608, 0.35325924, 0.12087147],
       [0.01832496, 0.35586487, 0.12314753],
       [0.0172972 , 0.35375211, 0.12048023],
       [0.01738468, 0.35311502, 0.12042207],
       [0.0176571 , 0.35287657, 0.12085276],
       [0.01798122, 0.35581008, 0.12248468],
       [0.01802397, 0.35500982, 0.12228495],
       [0.01743393, 0.35336867, 0.12060434],
       [0.01812533, 0.35564935, 0.12269947],
       [0.01792754, 0.35541555, 0.12224537],
       [0.01762541, 0.3533678 , 0.12096552],
       [0.01846844, 0.35499719, 0.12311762],
       [0.01854996, 0.35598946, 0.12361486],
       [0.01791653, 0.35400516, 0.12173323]])

In [18]:
#save contextual vector
np.savetxt("output_context_vector.txt",context_vector,fmt="%.4f")